name = "sumlec"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_GEMINI_API_KEY = "AIzaSyCLiFy4MQiKm02kRaFUM8BzSqvcAFUzhks"
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCRibKbn3qxwBSY6GpXRTLnlTMCVvbV4Qg"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "summarizelecture-ai.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "summarizelecture-ai"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "summarizelecture-ai.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "128494329212"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:128494329212:web:e958941578848d605f98f9"
POLAR_ACCESS_TOKEN = "polar_oat_XVFzaZkw9q3fIZVB3QJ9XXtRU5gpGjCuCixGn1w7nPQ"
POLAR_SANDBOX = "true"
NEXT_PUBLIC_BASE_URL = "https://summarizelectures.com"
